### ISSUE TITLE
Fossils and Arcehology, Binnie's Mod Links

### ISSUE THREAD

**Issue by YseraTheDreamer** [Aiidoneus/UnKnown-Legion-Reborn#2]
Fossils and Archeology: https://mods.curse.com/mc-mods/minecraft/223908-fossils-and-archeology-revival/2321502

Binnie's Mod: https://minecraft.curseforge.com/projects/binnies-mods
BinniePatcher: https://minecraft.curseforge.com/projects/binniepatcher

**Comment by Aiidoneus** [comment]
Fossils and Archeology has a bug that I can't seem to fix so that isn't added.

Binnie's mods/Forestry added

**Comment by YseraTheDreamer** [comment]
Magic Bees, Interfaces with: Botania and Thermal Expansion

https://minecraft.curseforge.com/projects/magic-bees
